CopaDoMundo/CopaDoMundo/Controllers/SelecoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CopaDoMundo.Models;
using PagedList;

namespace CopaDoMundo.Controllers
{
    public class SelecoesController : Controller
    {
        private CopaDoMundoEntities db = new CopaDoMundoEntities();

        // GET: Selecoes
        public ActionResult Index(int? pag)
        {
            return View(db.Selecoes1.OrderBy(s => s.Nome).ToList().ToList());
        }

        // GET: Selecoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Selecoes selecoes = db.Selecoes1.Find(id);
            if (selecoes == null)
            {
                return HttpNotFound();
            }
            return View(selecoes);
        }

        // GET: Selecoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Selecoes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSelecao,Nome,QtdTitulos,Bandeira,Descricao")] Selecoes selecoes)
        {
            if (ModelState.IsValid)
            {
                if (db.Selecoes1.Count() == 16)
                {
                    //Oitavas();
                    //exibir alerta de 16 seleções já cadastradas
                }
                else if (db.Selecoes1.Count() < 17)
                {
                    db.Selecoes1.Add(selecoes);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(selecoes);
        }


        // GET: Selecoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Selecoes selecoes = db.Selecoes1.Find(id);
            if (selecoes == null)
            {
                return HttpNotFound();
            }
            return View(selecoes);
        }

        // POST: Selecoes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSelecao,Nome,QtdTitulos,Bandeira,Descricao")] Selecoes selecoes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(selecoes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(selecoes);
        }

        // GET: Selecoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Selecoes selecoes = db.Selecoes1.Find(id);
            if (selecoes == null)
            {
                return HttpNotFound();
            }
            return View(selecoes);
        }

        // POST: Selecoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Selecoes selecoes = db.Selecoes1.Find(id);
            db.Selecoes1.Remove(selecoes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SortearOitavas()
        {
            List<Selecoes> lstSelecoes = new List<Selecoes>();
            lstSelecoes = db.Selecoes1.ToList();

            if (lstSelecoes.Count() == 16)
            {
                db.Jogos.RemoveRange(db.Jogos.Where(j => j.FaseId <= 8));
                db.SaveChanges();

                List<Selecoes> randomList = new List<Selecoes>();
                Jogos jogos;

                Random r = new Random();
                int randomIndex = 0;
                while (lstSelecoes.Count > 0)
                {
                    randomIndex = r.Next(0, lstSelecoes.Count); //Choose a random object in the list
                    randomList.Add(lstSelecoes[randomIndex]); //add it to the new, random list
                    lstSelecoes.RemoveAt(randomIndex); //remove to avoid duplicates
                }

                randomList.Count();

                for (int i = 0; i < randomList.Count(); i += 2)
                {
                    jogos = new Jogos();

                    jogos.SelecaoId1 = randomList[i].IdSelecao;
                    jogos.SelecaoId2 = randomList[i + 1].IdSelecao;
                    jogos.Gol1 = 0;
                    jogos.Gol2 = 0;
                    jogos.FaseId = 8;

                    db.Jogos.Add(jogos);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Oitavas", "Jogos");
        }

        public ActionResult RemoverTodas()
        {
            db.Jogos.RemoveRange(db.Jogos.Where(j => j.FaseId <= 8));
            db.SaveChanges();

            db.Selecoes1.RemoveRange(db.Selecoes1.Where(s => s.IdSelecao > 0));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CopaDoMundo/CopaDoMundo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Copa do Mundo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Copa do Mundo", "Index", "Selecoes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Início", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Selecoes", "Index", "Selecoes")</li>
                    <li>@Html.ActionLink("Oitavas", "Oitavas", "Jogos")</li>
                    <li>@Html.ActionLink("Quartas", "Quartas", "Jogos")</li>
                    <li>@Html.ActionLink("Semi", "Semi", "Jogos")</li>
                    <li>@Html.ActionLink("Terceiro", "Terceiro", "Jogos")</li>
                    <li>@Html.ActionLink("Final", "Final", "Jogos")</li>
                    @*<li>@Html.ActionLink("Fases", "Index", "Fases")</li>*@
                    @*<li>@Html.ActionLink("Contato", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="row panel">
        <div id="menu" class="col-xs-2">
            @*M E N U*@
        </div>
        <div class="container body-content col-xs-4">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Copa do Mundo</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>